### ISSUE TITLE
Not Active........... 

### ISSUE THREAD

**Issue by TejasRanjith** [AI-Group-202122/Group_001#6]
Hey guys, 
     I hope you guys didn't forget about the Group Repository so......
For those who want to know how the HTML code works. can see this file in the repository named "abc.html"
[https://github.com/AI-Group-202122/Group_001/blob/master/abc.html](url)

So I hope you guys will know something about HTML programming language because we have learned it in smaller classes.

Thanking you,
Yours Friendly

Tejas Ranjith

**Comment by TejasRanjith** [comment]
Please focus on it as it has been almost a lot of days since anyone has ever interacted with our group repository

**Comment by Harshil-Suthar** [comment]
i know man
